dependencies:
  - python=3.7
  - rasterio=1.1.0
  - geopandas=0.8.1
  - xarray=0.16.2
  - scipy=1.5.2
  - pip
  - pip:
      - citycatio==0.7.3
      - rioxarray==0.1.1
      - matplotlib-scalebar==0.7.2